### ISSUE TITLE
Circular property definition

### ISSUE THREAD

**Issue by mtide** [ozimov/yaml-properties-maven-plugin#6]
#### Execute cmd "mvn clean install", the following error occurred:

```java
org.apache.maven.plugin.MojoFailureException: Circular property definition: 

eureka.client.service-url.defaultZone=http://${security.user.name}:${security.user.password}@gclife-registry-peer1:13020/eureka/,http://${security.user.name}:${security.user.password}@gclife-registry-peer2:13021/eureka/ -> security.user.name=admin -> security.user.password=admin123 -> security.user.name=admin
```

Here's my yml file:

```yml
server:
  context-path: /uaa
  port: ${SERVER.PORT:13040}

eureka:
  instance:
    hostname: gclife-auth-service
    prefer-ip-address: true
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}
  client:
    service-url:
      defaultZone: http://${security.user.name}:${security.user.password}@gclife-registry-peer1:13020/eureka/,http://${security.user.name}:${security.user.password}@gclife-registry-peer2:13021/eureka/

spring:
  datasource:
    url: jdbc:postgresql://gclife-postgres:5432/gclife-base
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

security:
  user:
    name: admin
    password: admin123
```
